Server implemented PUT request
AbgarSim/Assistant pull request #2
Opened 2021-03-10 18:41 UTC by ABotnari

2021-03-11 16:29 UTC, AbgarSim commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +@RequestMapping(value = "/dummy")
value redundant here

2021-03-11 16:29 UTC, AbgarSim commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +	public ResponseEntity<Dummy> getDummyLong() {
rename method to `getDummy()` pls

2021-03-11 16:30 UTC, AbgarSim commented on Server/src/main/java/com/assistant/server/infrastructure/entity/Dummy.java
> +import javax.persistence.*;
don't use wildcard imports - bad practice, revert this

2021-03-11 16:31 UTC, AbgarSim commented on Server/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=validate
newline at the end of file

2021-03-11 16:31 UTC, AbgarSim requested changes
plz fix

2021-03-11 18:07 UTC, eugene-tech requested changes

2021-03-11 18:07 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +		return ResponseEntity.ok(service.updateDummy(id,dummy));
Please use auto format

2021-03-11 18:07 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/service/DummyService.java
> +	public Dummy getDummyNumber() {
Rename to getDummy

2021-03-11 18:07 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +	@PutMapping(value = "/update/{id}")
Not sure if we need 'value='

2021-03-12 15:13 UTC, AlexandrBotnari commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +@RequestMapping(value = "/dummy")
fixed

2021-03-12 15:14 UTC, AlexandrBotnari commented on Server/src/main/java/com/assistant/server/application/DummyController.java
> +	public ResponseEntity<Dummy> getDummyLong() {
done

2021-03-12 15:15 UTC, AlexandrBotnari commented on Server/src/main/java/com/assistant/server/infrastructure/entity/Dummy.java
> +import javax.persistence.*;
refactored

2021-03-12 15:16 UTC, AlexandrBotnari commented on Server/src/main/resources/application.properties
> +spring.jpa.hibernate.ddl-auto=validate
added

2021-03-12 15:41 UTC, AbgarSim commented
LGTM!

2021-03-12 15:41 UTC, merged

2021-03-12 15:44 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/service/DummyService.java
> +			repository.save(
Lets inline this operation

2021-03-12 15:44 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/service/DummyService.java
> +
Why do we need blank lines here

2021-03-12 15:47 UTC, eugene-tech commented on Server/src/main/java/com/assistant/server/service/DummyService.java
> +		final Dummy dummyById = repository.findDummyById(id);
Why its final